### ISSUE TITLE
No output PDF

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/canvas-syllabus-scraper#1]
I'm not super clear on how the PDF functionality is supposed to work. I'm able to get the .CSV output in a way that I expect though.

The docs don't really specify what is supposed to end up in the /pdf folder although based on the context, I'm assuming it's meant to grab PDF syllabi when people link them in the syllabus section in Canvas?

I'm not able to reproduce this assumed behaviour though. Any files that I add to my syllabus body in Canvas get ignored by the script - the internal logic that fails for me is `link.get('data-api-endpoint')` - this always gives me `None` as the endpoint and so far no file is ever downloaded or noted in the logs

**Comment by markoprodanovic** [comment]
@alisonmyers any ideas about this one? I can also bug Jeremy if this doesn't sound familiar

**Comment by alisonmyers** [comment]
I think this was an update I added... it is possible that none of the test courses in LS sandbox have a pdf in the right place though ...

**Comment by alisonmyers** [comment]
1. note - in helpers the url is static and uses test.instructure (won't be up to date with course?)

https://github.com/saud-learning-services/syllabus-scraper/blob/50d3d69cbbfb0877841dbeb89620b323340a41f3/src/helpers.py#L36 

2. The reference comes from data that should be in the file info from the link in the syllabus page - see https://canvas.instructure.com/doc/api/file.endpoint_attributes.html

**Comment by markoprodanovic** [comment]
I see. The issue I'm having is that the PDF's that I'm adding don't come back with that 'data-api-endpoint' attribute, only a 'href'. So I'm probably just not uploading to the correct spot.

**Comment by alisonmyers** [comment]
Ran it today - changing url above to ubc.instructure.com, and using no term filter (hit enter as indicated) - was working for me. Files downloaded to pdf folder.

**Comment by markoprodanovic** [comment]
Ran with 2018W2 and downloaded 2 items.

No bug, just misunderstood test scenario

**Comment by markoprodanovic** [comment]
Still experiencing a unknown problem. When adding files to syllabi and running shortly afterwards, getting no files and `extract_details` column in the CSV says:

> found 1 links and 0 syllabi in MarkoSandbox Marko Sandbox (47536): []

Behind the scenes, the reason these don't get picked up is because they don't have the attribute `data-api-endpoint` in the links.

But other courses with documents attached seem to be working just fine.

**Possible problem is that these files just take some time to appear in the backend.** Leaving this open for now to investigate further.

**Comment by markoprodanovic** [comment]
@markoprodanovic to try this again
